-- Properties Table
CREATE TABLE properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT,
  title TEXT,
  type TEXT,
  price TEXT,
  location TEXT,
  beds INT,
  baths INT,
  size TEXT,
  description TEXT,
  image TEXT,
  images TEXT[],
  status TEXT DEFAULT 'Active',
  hasPaymentPlan BOOLEAN DEFAULT FALSE,
  currency TEXT DEFAULT 'GH₵'
);

-- Inquiries Table
CREATE TABLE inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT,
  email TEXT,
  phone TEXT,
  message TEXT,
  propertyName TEXT,
  propertyId BIGINT,
  status TEXT DEFAULT 'New',
  date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Settings Table
CREATE TABLE settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stats JSONB DEFAULT '{"yearsExperience": "0", "propertiesListed": "0", "happyClients": "0", "awardsWon": "0"}'::jsonb,
  contact JSONB DEFAULT '{"phone": "", "email": "", "address": ""}'::jsonb,
  social JSONB DEFAULT '{"facebook": "", "instagram": "", "twitter": "", "linkedin": ""}'::jsonb
);

-- Users Table (For Admin Access)
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT,
  role TEXT DEFAULT 'admin'
);

-- Blog Posts Table
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT,
  excerpt TEXT,
  content TEXT,
  image TEXT,
  category TEXT,
  author TEXT,
  date DATE DEFAULT CURRENT_DATE
);

-- Newsletter Table
CREATE TABLE newsletter (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Insert initial admin user (Change password immediately!)
INSERT INTO users (email, password, name, role) 
VALUES ('admin@example.com', 'admin123', 'Admin User', 'admin');

-- Insert initial settings row
INSERT INTO settings (stats, contact, social) 
VALUES ('{"yearsExperience": "10", "propertiesListed": "500", "happyClients": "1200", "awardsWon": "15"}'::jsonb, '{}'::jsonb, '{}'::jsonb);
